services:
  devhabit.webapi:
    image: devhabit.webapi
    build:
      context: .
      dockerfile: DevHabit.WebApi/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      
  devhabit.aspire-dashboard:
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888